### ISSUE TITLE
Banner Section: Images are stretched due to the fixed height set. 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Oz-West-Garage-Doors#110]
Please set an image width and height and set cropped to true, please follow the design for the correct image dimensions, and height must be auto. 
![image](https://cloud.githubusercontent.com/assets/13363508/16406876/5461017c-3d43-11e6-9f51-51549f18a7cd.png)

**Comment by maehtitan** [comment]
Still not yet achieved perfectly coz bigger image uploaded will not fit the whole width. 
![image](https://cloud.githubusercontent.com/assets/13363508/16572817/804cd5d4-429f-11e6-88ff-88c4088c063a.png)

Have you set the right width to be cropped? 
![image](https://cloud.githubusercontent.com/assets/13363508/16572799/4d8b4c7a-429f-11e6-8133-18ee673db73e.png)

**Comment by p-sangchan** [comment]
Yes I have set it already

![image](https://cloud.githubusercontent.com/assets/18692062/16646313/9ee6fbf4-4453-11e6-836e-526ec08781cc.png)

**Comment by maehtitan** [comment]
@p-sangchan And Why is it that the dummy image I uploaded doesn't crop to the right height? I has a height set to 302
![image](https://cloud.githubusercontent.com/assets/13363508/16648349/2823adec-4466-11e6-8841-f8882b6e7600.png)
![image](https://cloud.githubusercontent.com/assets/13363508/16648353/3448c2f6-4466-11e6-87f4-661bacbaadc0.png)

**Comment by p-sangchan** [comment]
Please try to re-upload the image.

**Comment by maehtitan** [comment]
Image re uploaded but doesn't cropped properly.
