### ISSUE TITLE
Banner Section - Responsive Checking: Banner bullet navigation must be moved down when text is position below the banner image in 991px - 641px view port sizes.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Oz-West-Garage-Doors#126]
![image](https://cloud.githubusercontent.com/assets/13363508/16576463/0493f8fa-42c2-11e6-86fd-42928a6d0e00.png)

**Comment by p-sangchan** [comment]
Text banner still over the image on screen size between 991-641px

![image](https://cloud.githubusercontent.com/assets/18692062/16641788/1279cb6c-442e-11e6-9d65-ca3a298c5a4d.png)
