### ISSUE TITLE
Admin: As our implementation practice, all customizable items if its global must be located under Titan Theme Options and not under Business Details.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Oz-West-Garage-Doors#13]
![image](https://cloud.githubusercontent.com/assets/13363508/15814735/1cf0427e-2bfb-11e6-96ba-14a04c6556f1.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15814742/25cfa3ee-2bfb-11e6-91aa-99d0089eabc1.png)

**Comment by p-sangchan** [comment]
As per scope doc and it easier for user when need to setting header.

**Comment by roseliesromeo** [comment]
QA Lead: Global settings must be added in the Titan Theme options. Let us be consistent and adhere to the standard practices.
