### ISSUE TITLE
Product Single: Thumbnail image must not be cropped and should be shown completely.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Oz-West-Garage-Doors#143]
![image](https://cloud.githubusercontent.com/assets/13363508/16678402/561980e0-4511-11e6-9f3b-24e0f4b36a1f.png)

**Comment by p-sangchan** [comment]
Fixed, It must re-upload image before test.

**Comment by maehtitan** [comment]
@p-sangchan No changes has been made. Created another test data coz you deleted the previous one.
![image](https://cloud.githubusercontent.com/assets/13363508/16752998/9c98ef06-4818-11e6-932c-aacb982be661.png)

**Comment by p-sangchan** [comment]
@maehtitan It have to use new image by new upload instead use existing images.

**Comment by maehtitan** [comment]
@p-sangchan I already added new image, coz you removed the one I added.
