### ISSUE TITLE
Header Section: Title or tooltip must not be shown in all text elements it is only be visible in images.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Oz-West-Garage-Doors#3]
![image](https://cloud.githubusercontent.com/assets/13363508/15812688/85d16982-2bea-11e6-9576-e5bfbb959a31.png)

**Comment by p-sangchan** [comment]
For the SEO, It have to title attribute for tag a element.

**Comment by maehtitan** [comment]
@p-sangchan Yes it is part of the SEO but in our implementation practice here all menu tooltip is completely hidden. Please see sample site here: http://unusualpetvets.stage.titanweb.com.au/
