### ISSUE TITLE
Homepage & to All Affected Pages: Alphabet list turns to number list when copying from the word doc sheet and pasting it in the WYSIWYG editor.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Oz-West-Garage-Doors#36]
![image](https://cloud.githubusercontent.com/assets/13363508/15843820/9f71a3b8-2c97-11e6-8ea2-8deb21049dc8.png)

**Comment by p-sangchan** [comment]
Now the editor can choose more options for list,

but not auto-detect, 

If we want to auto-detect we must change the editor by install new editor plugin.

if you have any suggestion or case study please let me know.

**Comment by maehtitan** [comment]
@p-sangchan Please remove the new editor plugin, just use the default WYSIWYG and just use the CSS for the inner ordered list to list-style-type: lower-alpha.

**Comment by maehtitan** [comment]
@p-sangchan Still not yet fixed. Parent ol must be numbered list and the nested ol must be the alphabet list
