### ISSUE TITLE
Testimonials: There is no breadcrumbs found as per design.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Oz-West-Garage-Doors#59]
![image](https://cloud.githubusercontent.com/assets/13363508/15847574/96cea9be-2cb9-11e6-8d0d-b3e34f0ce890.png)

**Comment by p-sangchan** [comment]
Breadcrumb should always display in each pages

**Comment by maehtitan** [comment]
@p-sangchan As much as possible we must follow the design.
