### ISSUE TITLE
Admin - Default WP post: Categories aren't matched in the front-end page, Blog is showing and no News and also the Ozwest Posts.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Oz-West-Garage-Doors#63]
![image](https://cloud.githubusercontent.com/assets/13363508/15848028/dc3a5e1e-2cbc-11e6-916e-44bd0c7cd070.png)

**Comment by p-sangchan** [comment]
Confirmed with TL, I've deleted 'Ozwest Posts' category. every post displaying on blog page are under 'News' category.

**Comment by roseliesromeo** [comment]
For consistency with the Menu name, page title as well as the slug, rename the category to Blogs.
![image](https://cloud.githubusercontent.com/assets/11186313/16290541/de435cf8-3930-11e6-9027-757159cf3ef0.png)
