### ISSUE TITLE
Custom Made Doors: Gallery thumbnails are missing when browser resizes from smaller resolution, navigate the photo first then open it in the open it back in desktop view.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Oz-West-Garage-Doors#94]
Please see video here to replicate the issue: http://screencast.com/t/QZMLrJ45avM

**Comment by maehtitan** [comment]
Issue still recurring.

**Comment by p-sangchan** [comment]
I have tested follow the following link on my PC and other PC.

It not seen like you and it working fine. 

can you please clear the cache or try on other PC whether it still recurring?

Thank you.

**Comment by maehtitan** [comment]
@p-sangchan This issue is obviously visible in video post above. Will give you another instruction below coz it is still recurring in my TL's pc, co-QA.

Steps to replicate:
1. Refresh the page.
2. Resize browser to smaller viewport sizes
3. Navigate to the next images.
4. Resize back the browser to its desktop view, there you can see the thumbnails are missing.

Hope it makes sense.

**Comment by maehtitan** [comment]
No changes has been made, issues still recurring.
